# Word Cloud server-config
data:
  data_dir: "data/PDFs"
  format: ".pdf"
  recursive: True

grobid:
  cache: True
  cache_dir: "data/xmls"
  operation_key: "processFulltextDocument"
  format: ".grobid.tei.xml"
  recursive: True

extract:
  dir: null
  element: null
  type: null
