# Word Cloud server-config
data:
  data_dir: "data/PDFs"
  format: ".pdf"
  recursive: True

grobid:
  cache: True
  cache_dir: "data/xmls"
  operation_key: "processFulltextDocument"
  format: ".grobid.tei.xml"
  recursive: True

image:
  width: 1000
  height: 1000
  cache_dir: "data/img/cloud_img"
  cache: True
  format: ".png"
  background: "white"
