# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      # Recursivamente también clona los submódulos
      with:
        submodules: recursive
    - name: Initialize submodules
      run: git submodule init
      working-directory: ./pdf_analyzer/api/grobid_client_python  # ajusta la ruta a tus submódulos
    - name: Update submodules
      run: git submodule update
      working-directory: ./pdf_analyzer/api/grobid_client_python  # ajusta la ruta a tus submódulos
    - name: Pdf-analyzer
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.5"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with unnitest
      run: |
        python -m unittest discover -s tests -p '*_test.py'
